FROM node:20-alpine AS builder

WORKDIR /app
COPY package*.json ./
COPY turbo.json ./
COPY prisma ./prisma
COPY apps/api/package.json ./apps/api/
COPY apps/web/package.json ./apps/web/

RUN npm install

# Copy source code
COPY . .

# Environment variables needed for build time
ARG NEXT_PUBLIC_API_URL
ENV NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}

# Build Web (Next.js)
RUN npm run build --workspace=apps/web

# Production image
FROM node:20-alpine AS runner
WORKDIR /app

ENV NODE_ENV=production

COPY --from=builder /app/apps/web/public ./apps/web/public
# Automatically leverage output traces to reduce image size (requires output: 'standalone' in next.config.ts)
COPY --from=builder /app/apps/web/.next/standalone ./
COPY --from=builder /app/apps/web/.next/static ./apps/web/.next/static

EXPOSE 3000

CMD ["node", "apps/web/server.js"]
